### ISSUE TITLE
Develop full sync capability so CSOs are projected/updated in MV

### ISSUE THREAD

**Issue by JayVDZ** [TetronIO/JIM#90]
Using a TDD approach, enable synchronisation rules to be evaluated as part of a Full Synchronisation run profile execution.

## Tasks

- [x] Implement way to control Metaverse object deletion logic (RemoveContributedAttributesOnObsoletion)
- [x] Implement way to control attribute recall after CSO deletion
- [x] Pending Export Objects are deleted when CSO state is confirmed to match
- [x] Connected System Objects are projected to the Metaverse when projection is selected and join rules result in no MVO match
- [x] Metaverse Objects are updated when an existing join is in place and CSO attributes are updated
- [x] Metaverse Objects are updated when a new join is established from a CSO and attributes are updated accordingly
- [x] Metaverse Objects are deleted when there's an existing join and the CSO is obsoleted after not appearing in the import (via MVO deletion rules)
- [x] Metaverse Objects are left intact when an existing join is broken as a result of a CSO obsoletion and MVO attributes updated accordingly
- [x] Connected System objects are deleted after an obsoletion is processed

## Dependencies

- [x] A way to control Metaverse object deletion logic
- [x] A way to control attribute recall after CSO deletion

## Notes

- MVO deletion rules implemented in ff3a5b6 (Manual, WhenLastConnectorDisconnected with optional grace period)
- Background job for processing scheduled MVO deletions tracked in #120
- Outbound sync (MVO changes → CSO updates) tracked in #121

**Comment by JayVDZ** [comment]
Commit 1ed2e76 fixes AttributeId not being set in PendingAttributeValueAdditions during sync rule mapping processing. This was causing the `MvoPendingAttributeValueAddsAllDataTypesTestAsync` test to fail.
