### ISSUE TITLE
Implement MV attribute priority

### ISSUE THREAD

**Issue by JayVDZ** [TetronIO/JIM#91]
## Problem Statement

When multiple connected systems import values for the same MVO attribute, we need a deterministic way to decide which value wins.

**Example scenario:**
- HR System imports `department` with value "Engineering"
- Corporate Directory imports `department` with value "IT Services"
- Which value should the MVO have?

Without explicit priority, the result depends on sync execution order — unpredictable and error-prone.

**Traditional ILM limitation:**
Many identity management systems use fallback logic where if the top-priority source doesn't provide a value, the system automatically falls back to the next source. This is problematic when you want to **assert null** — i.e., explicitly say "this attribute should have no value" from the authoritative source, without falling back to a secondary source.

### Current Behaviour

As noted in `SyncRuleMappingProcessor.cs`:
> *"NOTE: attribute priority has not been implemented yet and will come in a later effort. For now, all mappings will be applied, meaning if there are multiple mappings to a MVO attribute, the last to be processed will win."*

This "last-writer-wins" behaviour is intentionally temporary and will be replaced by proper priority resolution.

**Known limitation:** When attributes are recalled (CSO obsoleted with `RemoveContributedAttributesOnObsoletion=true`), the system does not attempt to find an alternative contributor from another connected system with inbound attribute flow for the same MVO attribute. This requires the attribute priority infrastructure. Until then, recalled attributes are simply cleared.

### Existing Infrastructure

- `ContributedBySystem` navigation property exists on `MetaverseObjectAttributeValue` — tracks which connected system contributed each attribute value
- `ContributedBySystemId` scalar FK (added Feb 2026, commit `41116255`) — explicit `int?` property that avoids the need to `.Include(ContributedBySystem)`. All 14 attribute creation paths in `SyncRuleMappingProcessor` now set this scalar FK via a `contributingSystemId` parameter. Recall logic in `SyncTaskProcessorBase` uses the scalar FK directly (`av.ContributedBySystemId == connectedSystemId`).

---

## Design Decision: Per-Attribute Numerical Priority

**Design approved — implementation deferred.**

### Options Considered

| Option | Description | Verdict |
|--------|-------------|---------|
| **A. System-Level Priority** | Each connected system has a priority number; highest-priority source wins for all attributes | Too coarse — can't have different priorities per attribute on the same system. **Ruled out.** |
| **B. Per-Attribute Numerical Priority** | Each import attribute flow has a numerical priority for its target MVO attribute | **Selected** |
| **C. Attribute Ownership** | Each MVO attribute has one owner; only the owner can update it | Too inflexible — doesn't support fallback scenarios. **Ruled out.** |

### Core Design

1. **Numerical priority per attribute contribution** — Each import sync rule mapping that targets an MVO attribute has a priority number (1 = highest priority, larger numbers = lower priority)

2. **Default behaviour (fallback chain)** — Evaluate contributing systems in priority order; use the first non-null value found

3. **Advanced option: "Null is a value"** — When enabled on a specific contribution, if that system contributes null/absent, stop evaluation immediately (no fallback). This allows explicitly asserting "no value" from the authoritative source.

### Example Configuration

```
MVO Attribute: department
+------------------------------------------------------------------+
| Priority | Connected System | Null Handling                      |
+----------+------------------+------------------------------------+
|    1     | HR System        | [x] Null is a value (no fallback)  |
|    2     | Corporate Dir    | [ ] Null is a value                |
|    3     | Self-Service AD  | [ ] Null is a value                |
+----------+------------------+------------------------------------+
```

**Behaviour:**
- If HR System provides "Engineering" → MVO gets "Engineering" (priority 1 wins)
- If HR System provides null and "Null is a value" is checked → MVO gets null (no fallback)
- If HR System provides null and "Null is a value" is unchecked → check Corporate Dir (priority 2)
- If Corporate Dir provides "IT Services" → MVO gets "IT Services"
- And so on down the chain...

### Design Decisions

- **Default priority**: When a new import mapping is created, assign the next available priority number (lowest priority)
- **Default null handling**: "Null is a value" = false (fallback behaviour, matching traditional ILM expectations)
- **UI placement**: Priority management accessible from both the sync rule page and a dedicated "Attribute Priority" view

---

## Schema Changes

```csharp
public class SyncRuleMapping
{
    // ... existing properties ...

    /// <summary>
    /// Priority for this attribute contribution when multiple systems import
    /// to the same MVO attribute. Lower numbers = higher priority (1 is highest).
    /// Only applicable to import sync rules.
    /// </summary>
    public int Priority { get; set; } = int.MaxValue; // Default: lowest priority

    /// <summary>
    /// When true, if this source contributes null/absent for this attribute,
    /// stop evaluation immediately without falling back to lower-priority sources.
    /// When false (default), null values are skipped and evaluation continues
    /// to the next priority level.
    /// </summary>
    public bool NullIsValue { get; set; } = false;
}
```

The `Priority` value is scoped to the target MVO attribute. When a new import mapping is created targeting an MVO attribute that already has contributors, the system should assign the next available priority number (max existing priority + 1).

---

### Attribute Priority Resolution (Inbound Sync)

```csharp
/// <summary>
/// Resolves the winning value for an MVO attribute when multiple systems contribute.
/// Called during inbound sync processing.
/// </summary>
object? ResolveAttributeValue(string mvoAttributeName, MetaverseObjectType objectType)
{
    // Get all import mappings targeting this MVO attribute, ordered by priority
    var contributions = GetImportMappingsForAttribute(mvoAttributeName, objectType)
        .OrderBy(m => m.Priority)
        .ToList();

    foreach (var contribution in contributions)
    {
        var value = GetContributedValue(contribution);

        if (value != null)
        {
            // Non-null value found - use it
            return value;
        }

        if (contribution.NullIsValue)
        {
            // Null contributed and "Null is a value" is enabled - stop here
            return null;
        }

        // Null contributed but fallback is allowed - continue to next priority
    }

    // No value found from any contributor
    return null;
}
```

---

### 1. Dedicated Attribute Priority Page

**Location:** Metaverse → Attribute Priority (new navigation item)

Centralised view of all MVO attributes with multiple contributors, with drag-and-drop priority reordering, inline "Null is a value" toggles, and object type filtering.

### 2. Import Sync Rule Mapping Editor

Priority context panel showing where the mapping sits in the priority chain (only shown if multiple contributors exist), with a link to the central Attribute Priority page and "Null is a value" in an Advanced Options accordion.

### 3. Sync Rule Summary View

Priority indicator column showing how many attributes in each import rule have multiple contributors.

---

### Phase 1: Schema and Model Changes

- [x] Add `ContributedBySystemId` scalar FK to `MetaverseObjectAttributeValue` (prerequisite — Feb 2026)
- [x] Thread `contributingSystemId` through all 14 attribute creation paths in `SyncRuleMappingProcessor`
- [ ] Add `Priority` property to `SyncRuleMapping` model (default: int.MaxValue)
- [ ] Add `NullIsValue` property to `SyncRuleMapping` model (default: false)
- [ ] Create database migration
- [ ] Update API DTOs
- [ ] Add API endpoint to get/set attribute priority order

### Phase 2: Attribute Priority Logic

- [ ] Create `AttributePriorityService` in `src/JIM.Application/Services/`
- [ ] Integrate into inbound sync processing (`SyncRuleMappingProcessor`)
- [ ] Auto-assign priority on new import mapping creation

### Phase 3: UI Updates

- [ ] Create Attribute Priority page (Metaverse → Attribute Priority)
- [ ] Add priority context panel to import sync rule mapping editor
- [ ] Add "Advanced Options" section to import mapping editor with "Null is a value" checkbox
- [ ] Add priority indicator column to sync rule list view

### Phase 4: Testing

- [ ] Unit tests for `AttributePriorityService`
- [ ] Integration tests for multi-source priority resolution
- [ ] Integration tests for NullIsValue behaviour

### Phase 5: Documentation

- [ ] Add user documentation for Attribute Priority page
- [ ] Add user documentation for NullIsValue setting

---

## Open Questions

1. **Priority assignment for bulk import rule creation** — When creating a sync rule with many attribute mappings, how should priorities be assigned? All mappings from same rule get same base priority? Interactive assignment during wizard?

2. **Priority conflict warnings** — Should we warn when a new mapping creates a multi-contributor situation? Or just show the priority context panel?

3. **Cross-object-type attribute priority** — Currently scoped per object type. Probably no need for global priority — keep scoped for simplicity.

---

## References

- [Drift Detection and Attribute Priority Design Document](docs/plans/DRIFT_DETECTION_AND_ATTRIBUTE_PRIORITY.md)
